### ISSUE TITLE
Nullpointer Exception

### ISSUE THREAD

**Issue by robert-fuess** [michael-rapp/Apriori#6]
I'm using following dataset as input with an minSupport of 0.5 and a minConfidence of 1.0 (Version 1.3.0):

0 1 2 3 
0 1 2 3 
0 1 3 4 5 
0 1 4 
0 1 4 

This dataset produces following NullpointerException:

`java.lang.NullPointerException
	at de.mrapp.apriori.modules.FrequentItemSetMinerModule.generateInitialItemSets(FrequentItemSetMinerModule.java:70)
	at de.mrapp.apriori.modules.FrequentItemSetMinerModule.findFrequentItemSets(FrequentItemSetMinerModule.java:230)
	at de.mrapp.apriori.tasks.FrequentItemSetMinerTask.findFrequentItemSets(FrequentItemSetMinerTask.java:104)
	at de.mrapp.apriori.Apriori.execute(Apriori.java:830)`

if one of the first two identical entrys is removed, the algorithm works fine:

0 1 2 3 
0 1 3 4 5 
0 1 4 
0 1 4

**Comment by michael-rapp** [comment]
I tried to reproduce your problem, but wasn't able to. I added additional unit tests to the project using both of the data sets you have posted. You can find the test for the problematic data set [here](https://github.com/michael-rapp/Apriori/blob/64cbdca1b0bffd73ce92eb6ff00b41e6877f9c58/src/test/java/de/mrapp/apriori/modules/FrequentItemSetMinerModuleTest.java#L110). It works fine!

Do you use the `DataIterator`, which is part of the project's unit tests? If yes, maybe there is  a formatting/encoding problem with your input file. If not, there is a bug in your custom implementation of the `Transaction` interface. The exception is thrown, because the transaction's iterator returns null for one of its elements. In case you are using your own implementation, I can take a look at it if you post the code here.

**Comment by robert-fuess** [comment]
I do use the Dataiterator from your unit tests but to get rid of the Nullpointer i had to change this method:

@Override
    public final Transaction<NamedItem> next() {
        return hasNext() ? new TransactionImplementation(nextLine) : null;
    }

to:

@Override
    public final Transaction<NamedItem> next() {
        return new TransactionImplementation(nextLine);
    }

**Comment by michael-rapp** [comment]
Still cannot reproduce it. The code you have posted is not the same as on the master or 1.3.0-development branch. The actual implementation of the `DataIterator`'s `next`-method is:

```java
    @Override
    public final Transaction<NamedItem> next() {
        if (hasNext()) {
            Transaction<NamedItem> transaction = new TransactionImplementation(nextLine);
            nextLine = null;
            return transaction;
        }

        throw new NoSuchElementException();
    }
```

**Comment by robert-fuess** [comment]
Ok now i got it. Started with 1.2.0 and copied the DataIterator from there. Afterwards the version in the pom was changed to 1.3.0 but the copied files from 1.2.0 were not updated...

**Comment by michael-rapp** [comment]
Ok, good to hear that it works now!
