### ISSUE TITLE
Cannot access de.mrapp.util.datastructure.SortedArraySet

### ISSUE THREAD

**Issue by goodFancier** [michael-rapp/Apriori#8]
Hi.  I had a some error: Cannot access de.mrapp.util.datastructure.SortedArraySet. Can you help me? 

This is my code:       double minSupport = 0.5;
				Apriori<Tag> apriori = new Apriori.Builder<Tag>(minSupport).create();
				Iterable<Transaction<Tag>> iterable = () -> new DataIterator(new File("sad.txt"));
				Output<Tag> output = apriori.execute(iterable);
				FrequentItemSets<Tag> frequentItemSets = output.getRuleSet();

**Comment by falcaopetri** [comment]
Hey, I just faced this problem while trying to use the library. It took a while but I figured out the problem, a workaround and (probably) the solution:

## tl;dr
> [michael-rapp/Apriori](https://github.com/michael-rapp/Apriori) depends on [michael-rapp/JavaUtil](https://github.com/michael-rapp/JavaUtil), but the transitive dependency is not being resolved. Add [michael-rapp/JavaUtil](https://github.com/michael-rapp/JavaUtil) as a dependency to your project.

## The problem
[michael-rapp/Apriori](https://github.com/michael-rapp/Apriori) internaly uses a `SortedArraySet` data structure, that resides in the `de.mrapp.util.datastructure` package. What took me a while to realize is that it's not the package at [michael-rapp/Apriori](https://github.com/michael-rapp/Apriori), but at [michael-rapp/JavaUtil](https://github.com/michael-rapp/JavaUtil).

The Apriori project depends on Michael's JavaUtil project, as you can see here: https://github.com/michael-rapp/Apriori/blob/2e8bb7df1b1e71c6bc78ff0528a480d7a55cbf50/build.gradle#L41

It you clone and build the Apriori project, everything works fine. The problem happens when you add it as a dependency on your project. In this case, `output.getRuleSet()` returns a `FrequentItemSets`, a class that inherits from `SortedArraySet`. Your project does not know about [michael-rapp/JavaUtil](https://github.com/michael-rapp/JavaUtil), and complains that it can't access `de.mrapp.util.datastructure.SortedArraySet`.

## The workaround
You can directly add [michael-rapp/JavaUtil](https://github.com/michael-rapp/JavaUtil) as a dependency on your project. The project's readme has the instructions both using Gradle and Maven.

## The (probable) solution
I got confused on why the indirect dependecy was not being solved, since this seems to be the expected behavior. But then I found this great answer at stackoverflow: [What's the difference between implementation and compile in Gradle?](https://stackoverflow.com/a/48388463) (the issue ended up being about Gradle's compile vs implementation and api).

As noted in [The Java Library Plugin#API and implementation separation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation),

> The plugin exposes two configurations that can be used to declare dependencies: api and implementation. The api configuration should be used to declare dependencies which are exported by the library API, whereas the implementation configuration should be used to declare dependencies which are internal to the component.

So the problem boils down to the usage of `implementation` instead of `api` here: https://github.com/michael-rapp/Apriori/blob/2e8bb7df1b1e71c6bc78ff0528a480d7a55cbf50/build.gradle#L41

---------------------------
I will submit a PR solving this. The alternative would be to add documentation to this project about explicitly including [michael-rapp/JavaUtil](https://github.com/michael-rapp/JavaUtil) as a dependency to your project, but I guess that's not the intended behavior.
